// src/routes/docs/+page.svelte
<script lang="ts">
  import { documents } from "../../db/docs";

</script>
<h1>Documents</h1>
<p>This page contains a list of the documents that I currently own so far.</p>
<ol>
  {#each documents as documentItem}
    <li>
      <h2 id="{documentItem.id}">
        <a href="{documentItem.documentLink}" target="_blank">
          {documentItem.docHeading}
        </a>
      </h2>
      <ul>
        {#each documentItem.arrayOfInfo as information}
          <li>{information}</li>
        {/each}
      </ul>
    </li>
  {/each}
</ol>

// app/pages/docs.vue
<template>
  <div>
    <h1>Documents</h1>
    <p>This page contains a list of the documents that I currently own so far.</p>
    <ol>
      <li v-for="item of documents" :Key="item.id">
        <h2 :id="item.id">
          <a :href="item.documentLink" target="_blank">
            {{ item.docHeading }}
          </a>
        </h2>
        <ul>
          <li v-for="info of item.arrayOfInfo" :key="info">
            {{ info }}
          </li>
        </ul>
      </li>
    </ol>
  </div>
</template>

<script lang="ts" setup>
import { documents } from "~/db/docs";
</script>
