// app/pages/about.vue
<template>
  <div>
    <h1>About me</h1>
    <p>I'm Thien, a bored 14 year old teenager who doesn't really have much better things to do.
      <br>
      That's why I do Fictional Googology, the study of numbers beyond the "absolute".
    </p>
    <p>
      I also do web development albeit poorly (as you can tell), you can see my projects on
      <a href="https://github.com/Thien-Hubbing">github</a>.
    </p>
  </div>
</template>

// src/routes/about/+page.svelte
<h1>About me</h1>
<p>I'm Thien, a bored 14 year old teenager who doesn't really have much better things to do.
  <br>
  That's why I do Fictional Googology, the study of numbers beyond the "absolute".
</p>
<p>
  I also do web development albeit poorly (as you can tell), you can see my projects on
  <a href="https://github.com/Thien-Hubbing">github</a>.
</p>
